exports.frontmatter = {
  path: '/borozna',
  lng: 'en',
  name: 'Borozna Mikhail Grigorievich',
  science: 'Belarusian art historian, art critic, photo artist. Ph.D. in History of Arts (1998). Rector of the Belarusian State Academy of Arts. Honorary Member of the Russian Academy of Arts',
  birthDate: 'November 20, 1962 (56 years old)',
  birthPlace: 'Rakushevo, Kruglyansky village council, Kruglyansky district, Mogilev region, BSSR, USSR',
  education: 'He graduated from Kruglyanskaya high school. In 1985 he graduated from the art-industrial faculty of the Belarusian State Academy of Arts',
  activity: {
    '1985-1992': 'From 1985 to 1992 worked as art editor of the publishing house "Belarus"',
    1992: 'Since 1992, after graduating from graduate school he has been working at the Belarusian Academy of Arts',
    '1994-1996': 'In 1994-1996 was a curator-art historian of the gallery of modern art in Vitebsk "Pushkin"',
    1996: 'In 1996 he participated in the exhibition “Belart” (Germany)',
    '1996-1998': 'From 1996 to 1998, he acted as head of the department of history and theory of art',
    1999: 'In 1999 he defended his thesis for obtaining a scientific degree of a candidate of art history on the topic “Development trends of Belarusian book graphics of the 1960s – mid 1990s: on materials of fiction” (in the Belarusian State Academy of Arts). Since 1999 - Vice-Rector for scientific and artistic work',
    2010: 'Since 2010 - Rector of the Belarusian State Academy of Arts',
  },
  family: '',
  death: '',
  exhibitions: {
    1995: '"ARTUNODISKUS", Vitebsk',
    2000: '"White frost". Museum of Contemporary Art, Minsk',
    2002: '"Center of Attraction". VIII Baltic Triennial of International Art, Vilnius, Lithuania, “Fragments of Lost Time”. Art Center "Gilbel", Minsk',
    2004: '"Bunker church-gallery", Düsseldorf (Germany)',
    2007: '"The Jubilee Opening Day" Exhibition for the 15th anniversary of the gallery "Tradition" them. Pryanishnikov, Svetlogorsk',
    2008: '"Industry of Light" Exhibition of Belarusian photos. Museum of the Belarusian State Academy of Arts, Minsk',
    2009: '"Ctrl+Art" Art exhibition of photographs. Republican Art Gallery of the Belarusian Union of Artists, Minsk',
    2010: '"Europe Plus" (with E. Kenigsberg). Gallery of the High Folk School of Vienna-Hietzing, Vienna, Austria\n"Reflections" Exhibition of Belarusian photography. Kyiv City Art Gallery "Lavra", Kiev, Ukraine',
    2011: '"Belarusian Still Life" Republican Art Gallery of the Belarusian Union of Artists, Minsk',
  },
  youtube: 'https://youtu.be/jT-Zq10ac8Q?t=54',
  authorImage: 'borozna.jpg',
  works: [
    'borozna_1.jpg',
    'borozna_2.jpg',
    'borozna_3.jpg',
    'borozna_4.jpg',
    'borozna_5.jpg',
    'borozna_6.jpg',
    'borozna_7.jpg',
  ],
};
