exports.frontmatter = {
  path: '/bulgak',
  lng: 'en',
  name: 'Bulgak Jan',
  science: 'Belarusian  photographer,he founders and chairman of the Vilna Photo Club, the editor of the magazines "Przegląd Fotograficzny", "Fotograf Polski"',
  birthDate: 'October 6, 1876',
  birthPlace: 'Ostashino near Novogrudok',
  education: 'Graduated from the classical gymnasium in Vilna. In 1897-1899 he studied philosophy at the Jagiellonian University in Krakow',
  activity: {
    1912: 'In 1912 opened a photo studio in Vilna on Portovaya 12',
    '1912-1915': 'In 1912-1915 by request of the magistrate he photographed monuments of the city’s architecture',
    1919: 'From 1919 he taught art photography at the Fine Arts Department of the University of Stefan Batory. Associate Professor (1939)\nIn 1919, he became one of the founders and chairman of the Vilna Photo Club.He led them until the beginning of the Second World War. He was one of the founders of the Polish Photo Club',
    '1935-1939': 'In 1935 - 1939 was one of the editors of the magazines "Przegląd Fotograficzny", "Fotograf Polski"',
    1945: 'In 1945 he moved to Warsaw . He performed about a thousand photographs of destroyed and rebuilding Warsaw, about 2,000 photographs of western lands annexed to Poland',
    1947: 'In 1947 he became the founder of the Union of Photographers of Poland',
  },
  family: '',
  death: 'February 4, 1950',
  exhibitions: {
    '1931-1936': 'Series of photo albums "Wędrówki fotografa"',
    1934: 'Photo illustrations for the book about Vilna Jerzy Remer',
    1935: 'Book about the journey from Vilna to Lake Naroche with 38 photographs',
    1937: 'Photo illustrations for the city guide of Julius Clos',
  },
  youtube: 'Ato3OAWjdDA',
  authorImage: 'bulgak.jpg',
  works: [
    'bulgak_1.jpg',
    'bulgak_2.jpg',
    'bulgak_3.jpg',
    'bulgak_4.jpg',
    'bulgak_5.jpg',
    'bulgak_6.jpg',
    'bulgak_7.jpg',
  ],
};
