exports.frontmatter = {
  path: '/dashkevich',
  lng: 'en',
  name: 'Dashkevich Lev Urbanovich',
  science: 'Belarusian photographer, publicist, teacher, scientist, inventor',
  birthDate: 'February 12, 1882',
  birthPlace: 'Minsk',
  education: 'He was educated at the University of Dijon and the Graduate School of Graphic Arts in Paris (Department of Photography)',
  activity: {
    1911: 'From 1911 he began to publish in scientific journals (La Nature. Paris)',
    '1911-1920': 'In 1911-1920 he lived in the Caucasus, worked as a teacher of French, physics, natural science and other subjects in the gymnasiums of Eryvani (Yerevan)',
    1920: 'At the end of May 1920, he returned to Minsk. Since October 1920, the reader lectures on world literature and photography at the Minsk Institute of National Education',
    1921: 'In 1921 he worked in the Scientific Terminology Commission of the People\'s Commissariat of Education of the BSSR (natural section)',
    1923: 'In May-June 1923, he participated in an ethnographic expedition in Igumensk and Borisov Counties',
    '1923-1924': 'In 1923-1924, a science photographer at the medical faculty of BSU',
    1930: 'In 1930 he began working in the Minsk House of Technology, at the geographical faculty of the Belarusian State University',
    '1941-1944': 'In 1941-1944 he lived in an evacuation in Frunze (now Bishkek, Kyrgyzstan), worked in medical institutions. In September 1944 he returned to Minsk. He worked at the Institute of Theoretical Medicine and the Institute of Physiology',
  },
  family: 'In 1908, Lev Dashkevich married Zinaida Knizhnikova. Son Leonard (he was born in 1909)',
  death: 'Died December 4, 1957',
  exhibitions: [
    {
      year: 1923,
      name: 'Ethnographic expedition in the Igumen and Logoisk regions',
      photo: 'dashkevich_3.jpg',
    },
    {
      year: 1957,
      name: '"Light and shadow. Photos of Lev Dashkevich ”, Minsk',
      photo: 'dashkevich_4.jpg',
    },
  ],
  youtube: 'gTpMQjc9k74',
  authorImage: 'dashkevich.jpg',
  works: [
    'dashkevich_1.jpg',
    'dashkevich_2.jpg',
    'dashkevich_3.jpg',
    'dashkevich_4.jpg',
    'dashkevich_5.jpg',
    'dashkevich_6.jpg',
    'dashkevich_7.jpg',
    'dashkevich_8.jpg',
    'dashkevich_9.jpg',
  ],
};
