exports.frontmatter = {
  path: '/klinov',
  lng: 'en',
  name: 'Klinov Artur Aleksandrovich',
  science: 'Belarusian artist, designer, photographer, writer, screenwriter, editor-in-chief of the magazine “pARTisan” (2002)',
  birthDate: 'September 5, 1965',
  birthPlace: 'Minsk',
  education: 'He studied at children\'s art school number 1 in 1976-1980, and in art studios and workshops of Vladimir Tkachenko, Richard May and Vitaly Charnabrysava in 1978-1982.\nIn 1982-1987 he studied at the Faculty of Architecture of the Belarusian Polytechnic Institute (with teachers Galina Polyanskaya, Vyacheslav Angelov, Alexander Kollontai, etc.) and received a specialization in urban planning',
  activity: {
    1986: 'Since 1986, begins to organize numerous own and joint art exhibitions in Belarus and abroad. In the 1980s, in Minsk, he was an active participant in the non-conformist movement in Belarusian art: in 1987, he founded one of the first informal art groups in the BSSR “Community of Blo” (1987-1990) and was a participant in exhibitions of the band “Forma” (1987- 1990)',
    '1990s': 'In the 1990s he began to work with objects (he tried to create non-standard clear images) and installations (he used the principles of the philosophy of absurdity and existentialism). He became the author of the projects “Death of the Pioneer” (1995-2000), “Texts” and “50 buckets - masterpieces of world art” (1997-1999), as well as the interactive show “Columbarium of World Literature” (1998)',
    1998: 'In 1998, he became the founder and chairman of the Belarusian Association of Contemporary Art and the author of the idea of ​​the “Novinki” International Performance Festival (“NAVINKI”) in Belarus',
    2002: 'In 2002, he became the founder and chief editor of the art magazine (almanac of contemporary Belarusian culture) “pARTisan”, where he himself publishes his articles and photographs. He is the chief editor of the Internet portal partisanmag.by',
    2006: 'In 2006, he debuted in literature with the Russian-language novel “Minsk. City of the Sun ” (2006), and later published Belarusian-language novels “Shalom” (2010) and “Steklotara” (2013)',
    'February 4, 2008': 'On February 4, 2008, a presentation of the project “Collection of Partisan”, consisting of a series of albums of Belarusian contemporary art, took place. The first in this series was Arthur Klinov\'s album "The Twelve". It is a retrospective of the twelve most important projects for an artist over the past 12 years',
    2009: 'Since 2009, he began working in film as a screenwriter and artist. He is the art director of the films "Masakra" (2010) and "Hard Reboot" (2014)',
    2011: 'In 2011, he represented Belarus at the 54th International Venice Biennale (Italy), where he presented his installation of straw “Dinner”',
  },
  family: '',
  death: '',
  exhibitions: {
    1986: 'Personal apartment exhibition (Minsk, apartment of Artur Klinov)',
    1987: '“Superman\'s Spring Songs” (Minsk, apartment exhibition)',
    1994: 'Gallery "Vita Nova" (Minsk, Belarus)',
    1995: 'The Pioneer Death Project - The Sixth Line Independent Art Gallery (Minsk, Belarus)',
    1996: 'The project “Death of Pioneer-2” - the gallery of independent art “The Sixth Line” (Minsk, Belarus)',
    1998: 'The project "Columbarium of World Literature" - Center for Contemporary Art "Ujazdowski Palace" (Warsaw, Poland)',
    1999: 'Gallery "Officyna" (Szczecin, Poland)',
    2000: 'Forum "Kulturforum Rheine" - the castle Kloster Bentlage (Raine, Germany)\nThe house of the artist "Kunstlerhaus Boswil" (Basville, Switzerland)\nGallery "AT" (Poznan, Poland)',
    2001: 'The project "Palace for the Birds" - Center for Contemporary Art "Ujazdowski Palace" (Warsaw, Poland)',
    2003: 'The project "Sweet straw life" - gallery "RLBQ" (Marseille, France)\nGallery "Narod sobie Galeria" (Poznan, Poland)',
    2005: 'The project "Sweet straw life" - gallery "AT" (Poznan, Poland)',
    2006: 'The project "Mobile partisan shop" (Prague, Czech Republic)',
    2007: 'Projects "Alice in the country of mad tea drinking" and "City of the Sun" - gallery "Giedre Bartelt Galerie" (Berlin, Germany)',
    2008: 'Gallery "Zoja Gallery" (Warsaw, Poland)',
  },
  youtube: 'https://www.youtube.com/watch?v=BHGn4Zk49vY',
  authorImage: 'klinov.jpeg',
  works: [
    'klinov_1.jpg',
    'klinov_2.jpg',
    'klinov_3.jpg',
    'klinov_4.jpg',
    'klinov_5.jpg',
    'klinov_6.jpg',
    'klinov_7.jpg',
    'klinov_8.jpg',
    'klinov_9.jpeg',
    'klinov_10.jpg',
    'klinov_11.jpg',
    'klinov_12.jpg',
  ],
};
